  version: '3'
  services:
    frontend:
      build:
        context: ./frontend
      environment:
        - FLASK_APP=frontend.py
        - FLASK_DEBUG=True
      ports:
        - "5000:5000"
      volumes:
        - ./data/test.db:/app/test.db

    customer:
      build:
        context: ./customer
      environment:
        - FLASK_APP=customer.py
        - FLASK_DEBUG=True
      ports:
        - "5001:5001"
      volumes:
        - ./data/test.db:/app/test.db

    user:
      build:
        context: ./user
      environment:
        - FLASK_APP=user.py
        - FLASK_DEBUG=True
      ports:
        - "5002:5002"
      volumes:
        - ./data/test.db:/app/test.db
